# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw eta from full conditional posterior for sLDA
#'
#' @param zbar A D x K matrix with row d containing the mean number of draws of
#'   topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row sums to
#'   1.
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param sigma2 The residual variance.
#' @param mu0 A K x 1 vector of prior means for the regression coefficients.
#' @param sigma0 A K x K prior variance-covariance matrix for the regression
#'   coefficients.
NULL

#' Draw eta from full conditional posterior for sLDA-X
#'
#' @param zbar A D x K matrix with row d containing the mean number of draws of
#'   topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row sums to
#'   1.
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param x A D x (p + 1) matrix of additional predictors including a column of
#'   1's for the intercept.
#' @param sigma2 The residual variance.
#' @param mu0 A (K + p + 1) x 1 vector of prior means for the regression
#'   coefficients.
#' @param sigma0 A (K + p + 1) x (K + p + 1) prior variance-covariance matrix
#'   for the regression coefficients.
NULL

#' Compute logit
#' @param x A double
NULL

#' Compute inverse logit
#' @param x A double
NULL

#' Draw eta from full conditional posterior for logistic sLDA using
#'   Metropolis-Hastings (MH) algorithm
#'
#' @param zbar A D x K matrix with row d containing the mean number of draws of
#'   topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row sums to
#'   1.
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param eta_prev A p x 1 vector of the previous draw of the regression
#'   coefficients.
#' @param mu0 A K x 1 vector of prior means for the regression coefficients.
#' @param sigma0 A K x K prior variance-covariance matrix for the regression
#'   coefficients.
#' @param proposal_sd The proposal distribution standard deviations.
#' @param attempt The number of current attempted draws of eta by MH.
#' @param accept The number of accepted draws of eta by MH.
NULL

#' Draw eta from full conditional posterior for logistic sLDA-X using
#'   Metropolis-Hastings (MH) algorithm
#'
#' @param zbar A D x K matrix with row d containing the mean number of draws of
#'   topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row sums to
#'   1.
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param x A D x p matrix of additional predictors including a column of 1s
#'   for the intercept.
#' @param eta_prev A (K + p) x 1 vector of the previous draw of the
#'   regression coefficients.
#' @param mu0 A (K + p) x 1 vector of prior means for the regression
#'   coefficients.
#' @param sigma0 A (K + p) x (K + p) prior variance-covariance matrix for the
#'   regression coefficients.
#' @param proposal_sd The proposal distribution standard deviations.
#' @param attempt The number of current attempted draws of eta by MH.
#' @param accept The nnumber of accepted draws of eta by MH.
NULL

#' Draw sigma2 from full conditional posterior for sLDA
#'
#' @param D The number of documents.
#' @param a0 The prior shape parameter for \eqn{\sigma^2}.
#' @param b0 The prior scale parameter for \eqn{\sigma^2}.
#' @param zbar A D x K matrix with row \eqn{d} containing the mean number of
#'   draws of topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row
#'   sums to 1.
#' @param y A D x 1 vector of the outcome variable.
#' @param eta A K x 1 vector of regression coefficients.
#'
NULL

#' Draw sigma2 from full conditional posterior for sLDA-X
#'
#' @param D The number of documents.
#' @param a0 The prior shape parameter for \eqn{\sigma^2}.
#' @param b0 The prior scale parameter for \eqn{\sigma^2}.
#' @param zbar A D x K matrix with row \eqn{d} containing the mean number of
#'   draws of topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row
#'   sums to 1.
#' @param y A D x 1 vector of the outcome variable.
#' @param x A D x p matrix of additional predictors.
#' @param eta A K x 1 vector of regression coefficients.
#'
NULL

#' Estimate beta_k (on log-scale)
#'
#' @param k The topic label (i.e., the row of the K x V beta matrix).
#' @param V The number of terms in the corpus vocabulary.
#' @param wz_co A V x 1 vector of counts of the draws of each word for topic
#'   \eqn{k} over all documents.
#' @param gamma_ The hyperparameter for the Dirichlet priors on \eqn{\beta_k}.
#'
NULL

#' Estimate theta_d (on log scale)
#'
#' @param z_count A K x 1 vector of counts of topic draw in document \eqn{d}.
#' @param alpha_ The hyperparameter on the Dirichlet prior for \eqn{\theta_d}.
#' @param K The number of topics.
#'
NULL

#' Count topic-word co-occurences in corpus (ntopic x nvocab) (parallelizable)
#'
#' @param D The number of documents in the corpus.
#' @param K The number of topics.
#' @param V The number of terms in the corpus vocabulary.
#' @param doc_topic A D x max(\eqn{N_d}) matrix of topic assignments for
#'   the corpus.
#' @param doc_word A D x max(\eqn{N_d}) matrix of words for corpus.
#'
NULL

#' Draw zdn from full conditional distribution for sLDA
#'
#' @param yd A the outcome variable for document \eqn{d}.
#' @param zbar_d A K x 1 vector containing the empirical topic proportions in
#'   document \eqn{d} (should sum to 1).
#' @param eta A K x 1 vector of regression coefficients.
#' @param sigma2 The residual variance.
#' @param K The number of topics.
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document \eqn{d} excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word \eqn{m} in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
NULL

#' Draw zdn from full conditional distribution for sLDA-X
#'
#' @param yd A the outcome variable for document \eqn{d}.
#' @param x A D x p matrix of additional predictors.
#' @param zbar_d A K x 1 vector containing the empirical topic proportions in
#'   document \eqn{d} (should sum to 1).
#' @param eta A K x 1 vector of regression coefficients.
#' @param sigma2 The residual variance.
#' @param K The number of topics.
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document \eqn{d} excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word \eqn{m} in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
NULL

#' Draw zdn from full conditional distribution for sLDA with binary outcome
#'
#' @param yd A the outcome variable for document \eqn{d}.
#' @param zbar_d A K x 1 vector containing the empirical topic proportions in
#'   document \eqn{d} (should sum to 1).
#' @param eta A K x 1 vector of regression coefficients.
#' @param K The number of topics.
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document \eqn{d} excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word \eqn{m} in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
NULL

#' Draw zdn from full conditional distribution for sLDA-X with binary outcome
#'
#' @param yd A the outcome variable for document \eqn{d}.
#' @param x A D x p matrix of additional predictors.
#' @param zbar_d A K x 1 vector containing the empirical topic proportions in
#'   document \eqn{d} (should sum to 1).
#' @param eta A (p + K) x 1 vector of regression coefficients.
#' @param K The number of topics.
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document \eqn{d} excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word \eqn{m} in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
NULL

#' Draw zdn from full conditional distribution for LDA
#'
#' @param K The number of topics.
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document \eqn{d} excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word \eqn{m} in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
NULL

#' Compute WAIC for all outcomes.
#'
#' @param D The number of documents.
#' @param iter The current iteration of the chain.
#' @param ll_pred loglike_pred A m x D matrix of log-predictive likelihoods.
NULL

#' Sample from multivariate Gaussian N(\eqn{\mu}, \eqn{\Sigma})
#'
#' @param n The number of samples to draw.
#' @param mu The mean vector of the distribution (column vector).
#' @param sigma The variance-covariance matrix of the distribution.
#' @export
rmvnorm_cpp <- function(n, mu, sigma) {
    .Call(`_psychlda_rmvnorm_cpp`, n, mu, sigma)
}

#' Compute full conditional log-posterior of eta for logistic sLDA
#'
#' @param zbar A D x K matrix with row d containing the mean number of draws of
#'   topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row sums to
#'   1.
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param mu0 A K x 1 vector of prior means for the regression coefficients.
#' @param sigma0 A K x K prior variance-covariance matrix for the regression
#'   coefficients.
#' @export
eta_logpost_logit <- function(zbar, y, eta, mu0, sigma0) {
    .Call(`_psychlda_eta_logpost_logit`, zbar, y, eta, mu0, sigma0)
}

#' Compute full conditional log-posterior of eta for logistic sLDA-X
#'
#' @param zbar A D x K matrix with row d containing the mean number of draws of
#'   topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row sums to
#'   1.
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param x A D x p matrix of additional predictors including a column of
#'   1's for the intercept.
#' @param mu0 A (K + p) x 1 vector of prior means for the regression
#'   coefficients.
#' @param sigma0 A (K + p) x (K + p) prior variance-covariance matrix
#'   for the regression coefficients.
#' @export
eta_logpost_logitx <- function(zbar, y, x, eta, mu0, sigma0) {
    .Call(`_psychlda_eta_logpost_logitx`, zbar, y, x, eta, mu0, sigma0)
}

#' Collapsed Gibbs sampler for the sLDA model
#'
#' @include slda-class.R
#'
#' @param m The number of iterations to run the Gibbs sampler.
#' @param burn The number of iterations to discard as the burn-in period.
#' @param y A D x 1 vector of outcomes to be predicted.
#' @param docs A D x max(\eqn{N_d}) matrix of word indices for all documents.
#' @param w A D x V matrix of counts for all documents and vocabulary terms.
#' @param K The number of topics.
#' @param mu0 A K x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A K x K variance-covariance matrix for the prior on the
#'   regression coefficients.
#' @param eta_start A K x 1 vector of starting values for the regression
#'   coefficients.
#' @param constrain_eta A logical (default = \code{FALSE}): If \code{TRUE}, the
#'   regression coefficients will be constrained so that they are in descending
#'   order; if \code{FALSE}, no constraints will be applied.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions
#'   (default: 0.1).
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities (default: 1.01).
#' @param a0 The shape parameter for the prior on sigma2 (default: 0.001)
#' @param b0 The scale parameter for the prior on sigma2 (default: 0.001)
#' @param verbose Should parameter draws be output during sampling? (default:
#'   \code{FALSE}).
#' @param display_progress Should percent progress of sampler be displayed
#'   (default: \code{FALSE}). Recommended that only one of \code{verbose} and
#'   \code{display_progress} be set to \code{TRUE} at any given time.
#' @export
gibbs_slda <- function(m, burn, y, docs, w, K, mu0, sigma0, eta_start, constrain_eta = FALSE, alpha_ = 0.1, gamma_ = 1.01, a0 = 0.001, b0 = 0.001, verbose = FALSE, display_progress = FALSE) {
    .Call(`_psychlda_gibbs_slda`, m, burn, y, docs, w, K, mu0, sigma0, eta_start, constrain_eta, alpha_, gamma_, a0, b0, verbose, display_progress)
}

#' Collapsed Gibbs sampler for the sLDA-X model
#'
#' @include slda-class.R
#'
#' @param m The number of iterations to run the Gibbs sampler.
#' @param burn The number of iterations to discard as the burn-in period.
#' @param y A D x 1 vector of outcomes to be predicted.
#' @param x A D x p matrix of additional predictors (no column of 1's for the
#'   intercept).
#' @param docs A D x max(\eqn{N_d}) matrix of word indices for all documents.
#' @param w A D x V matrix of counts for all documents and vocabulary terms.
#' @param K The number of topics.
#' @param mu0 A K x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A (K + p + 1) x (K + p + 1) variance-covariance matrix for the
#'   prior on the regression coefficients. The first p + 1 columns/rows
#'   correspond to predictors in X, while the last K columns/rows correspond to
#'   the K topic means.
#' @param eta_start A (K + p + 1) x 1 vector of starting values for the
#'   regression coefficients. The first p + 1 elements correspond to predictors
#'   in X, while the last K elements correspond to the K topic means.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions
#'   (default: 0.1).
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities (default: 1.01).
#' @param a0 The shape parameter for the prior on sigma2 (default: 0.001)
#' @param b0 The scale parameter for the prior on sigma2 (default: 0.001)
#' @param verbose Should parameter draws be output during sampling? (default:
#'   \code{FALSE}).
#' @param display_progress Should percent progress of sampler be displayed
#'   (default: \code{FALSE}). Recommended that only one of \code{verbose} and
#'   \code{display_progress} be set to \code{TRUE} at any given time.
#' @export
gibbs_sldax <- function(m, burn, y, x, docs, w, K, mu0, sigma0, eta_start, alpha_ = 0.1, gamma_ = 1.01, a0 = 0.001, b0 = 0.001, verbose = FALSE, display_progress = FALSE) {
    .Call(`_psychlda_gibbs_sldax`, m, burn, y, x, docs, w, K, mu0, sigma0, eta_start, alpha_, gamma_, a0, b0, verbose, display_progress)
}

#' Posterior predictive log-likelihood for sLDA logistic
#'
#' @param zbar A D x K matrix with row \eqn{d} containing the mean number of
#'   draws of topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row
#'   sums to 1.
#' @param eta A K x 1 vector of regression coefficients.
#' @export
post_pred_slda_logit <- function(zbar, eta) {
    .Call(`_psychlda_post_pred_slda_logit`, zbar, eta)
}

#' Posterior predictive log-likelihood for sLDA-X logistic
#'
#' @param x A D x p matrix of additional predictors.
#' @param zbar A D x K matrix with row \eqn{d} containing the mean number of
#'   draws of topics \eqn{z_1, \ldots, z_K} in document \eqn{d} where each row
#'   sums to 1.
#' @param eta A (p + K) x 1 vector of regression coefficients.
#' @export
post_pred_sldax_logit <- function(x, zbar, eta) {
    .Call(`_psychlda_post_pred_sldax_logit`, x, zbar, eta)
}

#' Effective number of parameters for WAIC
#'
#' @param loglike_pred A m x 1 matrix of log-predictive likelihoods.
#' @export
pwaic_d <- function(loglike_pred) {
    .Call(`_psychlda_pwaic_d`, loglike_pred)
}

#' WAIC in sLDA logistic for observation y_d
#'
#' @param loglike_pred A m x 1 matrix of log-predictive likelihoods for y_d.
#' @param p_eff The contributions to the effective number of parameters from
#'   obs y_d.
#' @export
waic_d <- function(loglike_pred, p_effd) {
    .Call(`_psychlda_waic_d`, loglike_pred, p_effd)
}

#' Collapsed Gibbs sampler for the sLDA-X model with a binary outcome
#'
#' @include slda-class.R
#'
#' @param m The number of iterations to run the Gibbs sampler.
#' @param burn The number of iterations to discard as the burn-in period.
#' @param y A D x 1 vector of binary outcomes (0/1) to be predicted.
#' @param docs A D x max(\eqn{N_d}) matrix of word indices for all documents.
#' @param w A D x V matrix of counts for all documents and vocabulary terms.
#' @param K The number of topics.
#' @param mu0 A K x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A K x K variance-covariance matrix for the prior on the
#'   regression coefficients.
#' @param eta_start A K x 1 vector of starting values for the regression
#'   coefficients.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions
#'   (default: 0.1).
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities (default: 1.01).
#' @param proposal_sd A vector of proposal standard deviations for drawing the
#'   regression coefficients, N(0, proposal_sd) (default: 0.2).
#' @param verbose Should parameter draws be output during sampling? (default:
#'   \code{FALSE}).
#' @param display_progress Should percent progress of sampler be displayed
#'   (default: \code{FALSE}). Recommended that only one of \code{verbose} and
#'   \code{display_progress} be set to \code{TRUE} at any given time.
#' @export
gibbs_slda_logit <- function(m, burn, y, docs, w, K, mu0, sigma0, eta_start, proposal_sd, alpha_ = 0.1, gamma_ = 1.01, verbose = FALSE, display_progress = FALSE) {
    .Call(`_psychlda_gibbs_slda_logit`, m, burn, y, docs, w, K, mu0, sigma0, eta_start, proposal_sd, alpha_, gamma_, verbose, display_progress)
}

#' Collapsed Gibbs sampler for the sLDA-X model with a binary outcome
#'
#' @include slda-class.R
#'
#' @param m The number of iterations to run the Gibbs sampler.
#' @param burn The number of iterations to discard as the burn-in period.
#' @param y A D x 1 vector of binary outcomes (0/1) to be predicted.
#' @param x A D x p matrix of additional predictors (no column of 1s for
#'   intercept).
#' @param docs A D x max(\eqn{N_d}) matrix of word indices for all documents.
#' @param w A D x V matrix of counts for all documents and vocabulary terms.
#' @param K The number of topics.
#' @param mu0 A K x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A (K + p + 1) x (K + p + 1) variance-covariance matrix for the
#'   prior on the regression coefficients. The first p + 1 columns/rows
#'   correspond to predictors in X, while the last K columns/rows correspond to
#'   the K topic means.
#' @param eta_start A (K + p) x 1 vector of starting values for the
#'   regression coefficients. The first p elements correspond to predictors
#'   in X, while the last K elements correspond to the K topic means.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions
#'   (default: 0.1).
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities (default: 1.01).
#' @param proposal_sd The proposal standard deviation for drawing the
#'   regression coefficients, N(0, proposal_sd) (default: 0.2).
#' @param verbose Should parameter draws be output during sampling? (default:
#'   \code{FALSE}).
#' @param display_progress Should percent progress of sampler be displayed
#'   (default: \code{FALSE}). Recommended that only one of \code{verbose} and
#'   \code{display_progress} be set to \code{TRUE} at any given time.
#' @export
gibbs_sldax_logit <- function(m, burn, y, x, docs, w, K, mu0, sigma0, eta_start, proposal_sd, alpha_ = 0.1, gamma_ = 1.01, verbose = FALSE, display_progress = FALSE) {
    .Call(`_psychlda_gibbs_sldax_logit`, m, burn, y, x, docs, w, K, mu0, sigma0, eta_start, proposal_sd, alpha_, gamma_, verbose, display_progress)
}

#' Collapsed Gibbs sampler for the LDA model
#'
#' @include slda-class.R
#'
#' @param m The number of iterations to run the Gibbs sampler.
#' @param burn The number of iterations to discard as the burn-in period.
#' @param docs A D x max(\eqn{N_d}) matrix of word indices for all documents.
#' @param w A D x V matrix of counts for all documents and vocabulary terms.
#' @param K The number of topics.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions
#'   (default: 0.1).
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities (default: 1.01).
#' @param display_progress Should percent progress of sampler be displayed
#'   (default: \code{FALSE}).
#' @export
gibbs_lda <- function(m, burn, docs, w, K, alpha_ = 0.1, gamma_ = 1.01, display_progress = FALSE) {
    .Call(`_psychlda_gibbs_lda`, m, burn, docs, w, K, alpha_, gamma_, display_progress)
}

#' Simulate data from the sLDA model
#'
#' @param D The number of documents in the corpus.
#' @param V The number of terms in the corpus vocabulary.
#' @param N A D x 1 vector of the number of words in each document.
#' @param K The number of topics.
#' @param theta A D x K matrix of topic proportions (each row must sum to 1).
#' @param beta A K x V matrix of word probabilities per topic (each row must
#'   sum to 1).
#'
#' @export
sim_slda <- function(D, V, N, K, theta, beta, eta, sigma2) {
    .Call(`_psychlda_sim_slda`, D, V, N, K, theta, beta, eta, sigma2)
}

