# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample from multivariate Gaussian N(\eqn{\mu}, \eqn{\Sigma})
#'
#' @param n The number of samples to draw.
#' @param mu The q x 1 mean vector of the distribution (column vector).
#' @param sigma The q x q variance-covariance matrix of the distribution.
#'
#' @return A n x q matrix of random draws.
NULL

#' Get the top number of observations
#'
#' @param v A row vector of values to be tabulated.
#'
#' @return A map of (values, frequencies)
NULL

#' Draw eta from full conditional posterior for sLDA/sLDAX/MLR models
#'
#' @param w A D x q matrix containing a predictor model matrix of assumed form
#'   (X, Zbar, XZbarInteractions).
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param sigma2 The residual variance.
#' @param mu0 A q x 1 vector of prior means for the regression coefficients.
#' @param sigma0 A q x q prior variance-covariance matrix for the regression
#'   coefficients.
#'
#' @return A q x 1 vector of draws of eta.
NULL

#' Compute inverse logit
#' @param x A double
#'
#' @return Inverse-logit(x) on probability scale.
NULL

#' Log-likelihood for logistic regression for observation d
#'
#' @param yd An integer 0/1 outcome to be predicted.
#' @param muhatd A double predicted outcome on logit scale.
#'
#' @return The current log-likelihood for observation d.
NULL

#' Log-likelihood for logistic regression
#'
#' @param y A D x 1 vector of 0/1 outcomes to be predicted.
#' @param w A D x q matrix containing a predictor model matrix.
#' @param eta A q x 1 vector of regression coefficients.
#'
#' @return The current log-likelihood.
NULL

#' Log-posterior for regression coefficients with normal prior
#'
#' @param ll A double of the current log-likelihood.
#' @param eta A q x 1 vector of regression coefficients.
#' @param mu0 A q x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A q x q variance-covariance matrix for the prior on the
#'   regression coefficients.
#'
#' @return The current log-posterior.
NULL

#' Compute full conditional log-posterior of eta for logistic sLDA/sLDAX/regression
#'
#' @param w A D x q matrix containing a predictor model matrix of assumed form
#'   (X, Zbar, XZbarInteractions).
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param eta A q x 1 vector of regression coefficients
#' @param mu0 A q x 1 vector of prior means for the regression coefficients.
#' @param sigma0 A q x q prior variance-covariance matrix for the regression
#'   coefficients.
#'
#' @return The full conditional log-posterior density of eta.
NULL

#' Draw eta from full conditional posterior for logistic sLDA/sLDAX/regression
#'   using Metropolis-Hastings (MH) algorithm
#'
#' @param w A D x q matrix containing a predictor model matrix of assumed form
#'   (X, Zbar, XZbarInteractions).
#' @param y A D x 1 vector of the outcome variable for each document.
#' @param eta_prev A q x 1 vector of the previous draw of the regression
#'   coefficients.
#' @param mu0 A q x 1 vector of prior means for the regression coefficients.
#' @param sigma0 A q x q prior variance-covariance matrix for the regression
#'   coefficients.
#' @param proposal_sd A q x 1 vector of proposal distribution standard deviations.
#' @param attempt A vector of the number of current attempted draws of eta.
#' @param accept A vector of the number of accepted draws of eta.
#'
#' @return A q x 1 vector of draws for eta.
NULL

#' Draw sigma2 from full conditional posterior for sLDA/sLDAX/MLR
#'
#' @param a0 The prior shape parameter for \eqn{\sigma^2}.
#' @param b0 The prior scale parameter for \eqn{\sigma^2}.
#' @param w A D x q matrix containing a predictor model matrix of assumed form
#'   (X, Zbar, XZbarInteractions).
#' @param y A D x 1 vector of the outcome variable.
#' @param eta A q x 1 vector of regression coefficients.
#'
#' @return A draw for \eqn{\sigma^2}.
NULL

#' Compute log-numerator vector for sampling zdn from full conditional distribution for LDA
#'
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document d excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word m in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#' @param alpha_ The hyperparameter on the Dirichlet prior for \eqn{\theta_d}.
#' @param gamma_ The hyperparameter for the Dirichlet priors on \eqn{\beta_k}.
#'
#' @return A K x 1 vector of the log-numerator from the LDA model to sample zdn.
NULL

#' Draw zdn from full conditional distribution for LDA/sLDA/sLDAX
#'
#' @param log_num A K x 1 vector of the log-numerator for sampling from topics
#'   1, ..., K.
#'
#' @return Indicator for the topic draw from {1, 2, ..., K}.
NULL

#' Draw zdn from full conditional distribution for LDA
#'
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document d excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word m in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
#' @return Indicator for the topic draw from {1, 2, ..., K}.
NULL

#' Draw zdn from full conditional distribution for sLDA/sLDAX
#'
#' @param yd The outcome variable for document \eqn{d}.
#' @param w_d A q x 1 vector containing row d of the predictor model matrix of
#'   assumed form (X, Zbar, XZbarInteractions).
#' @param eta A q x 1 vector of regression coefficients.
#' @param sigma2 The residual variance.
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document d excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word m in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
#' @return Indicator for the topic draw from {1, 2, ..., K}.
NULL

#' Draw zdn from full conditional distribution for sLDA/sLDAX with binary outcome
#'
#' @param yd A the outcome variable for document d.
#' @param w_d A q x 1 vector containing row d of the predictor model matrix of
#'   assumed form (X, Zbar, XZbarInteractions).
#' @param eta A q x 1 vector of regression coefficients.
#' @param V The number of terms in the corpus vocabulary.
#' @param ndk_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} in
#'   document d excluding the current word \eqn{w_n} from the counts.
#' @param nkm_n A K x 1 vector of counts of topic \eqn{k = 1, \ldots, K} and
#'   word m in the corpus excluding the current word \eqn{w_n} from the
#'   counts.
#' @param nk_n A K x 1 vector of counts of draws of topic
#'   \eqn{k = 1, \ldots, K} in the corpus excluding the current word \eqn{w_n}
#'   from the counts.
#'
#' @return Indicator for the topic draw from {1, 2, ..., K}.
NULL

#' Posterior predictive likelihood for sLDA/sLDAX/MLR
#'
#' @param w A D x q matrix of additional predictors.
#' @param eta A q x 1 vector of regression coefficients.
#' @param sigma2 The residual variance.
#'
#' @return Posterior predictive likelihood.
NULL

#' Posterior predictive likelihood for logistic sLDA/sLDAX/regression
#'
#' @param w A D x q matrix of additional predictors.
#' @param eta A q x 1 vector of regression coefficients.
#' @return Predictive posterior likelihood of all D observations.
NULL

#' Contribution to effective number of parameters for WAIC from observation y_d
#'
#' @param like_pred A m x 1 vector of predictive likelihoods (NOT log-likelihoods).
#' @export
#' @return The contribution of y_d (its predictive posterior likelihood variance)
#'   to the effective number of parameters.
NULL

#' WAIC for observation y_d
#'
#' @param like_pred A m x 1 vector of predictive likelihoods (NOT log-likelihoods) for y_d.
#' @param p_effd The contribution to the effective number of parameters from
#'   obs y_d.
#' @return WAIC contribution for observation d (on deviance scale).
NULL

#' Log-likelihood for MLR
#'
#' @param y A D x 1 vector of outcomes to be predicted.
#' @param w A D x q matrix containing a predictor model matrix.
#' @param eta A q x 1 vector of regression coefficients.
#' @param sigma2 The current draw of the residual variance of y.
#'
#' @return The current log-likelihood.
NULL

#' Log-likelihood for LDA model
#'
#' @param zdocs A D x max(\eqn{N_d}) matrix of topic indicators for all documents.
#' @param docs A D x max(\eqn{N_d}) matrix of word indicators for all documents.
#' @param theta A D x K matrix of the current estimates of the document topic proportions.
#' @param beta a K x V matrix of the current estimates of the word-topic probabilities.
#' @param docs_index A vector of length D containing elements 1, 2, ..., D.
#' @param N A vector of length D containing the number of words in each document.
#'
#' @return The current log-likelihood.
NULL

#' Log-likelihood for sLDA/sLDAX model
#'
#' @param y A D x 1 vector of outcomes to be predicted.
#' @param w A D x q matrix containing a predictor model matrix of assumed form
#'   (X, Zbar, XZbarInteractions).
#' @param eta A q x 1 vector of regression coefficients.
#' @param sigma2 The current draw of the residual variance of y.
#' @param zdocs A D x max(\eqn{N_d}) matrix of topic indicators for all documents.
#' @param docs A D x max(\eqn{N_d}) matrix of word indicators for all documents.
#' @param theta A D x K matrix of the current estimates of the document topic proportions.
#' @param beta a K x V matrix of the current estimates of the word-topic probabilities.
#' @param docs_index A vector of length D containing elements 1, 2, ..., D.
#' @param N A vector of length D containing the number of words in each document.
#'
#' @return The current log-likelihood.
NULL

#' Log-likelihood for logistic sLDA/sLDAX model
#'
#' @param y A D x 1 vector of outcomes to be predicted.
#' @param w A D x q matrix containing a predictor model matrix of assumed form
#'   (X, Zbar, XZbarInteractions).
#' @param eta A q x 1 vector of regression coefficients.
#' @param zdocs A D x max(\eqn{N_d}) matrix of topic indicators for all documents.
#' @param docs A D x max(\eqn{N_d}) matrix of word indicators for all documents.
#' @param theta A D x K matrix of the current estimates of the document topic proportions.
#' @param beta a K x V matrix of the current estimates of the word-topic probabilities.
#' @param docs_index A vector of length D containing elements 1, 2, ..., D.
#' @param N A vector of length D containing the number of words in each document.
#'
#' @return The current log-likelihood.
NULL

#' Log-posterior for normal outcome regression
#'
#' @param ll A double of the current log-likelihood.
#' @param eta A q x 1 vector of regression coefficients.
#' @param sigma2 The current draw of the residual variance of y.
#' @param mu0 A q x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A q x q variance-covariance matrix for the prior on the
#'   regression coefficients.
#' @param a0 The shape parameter for the prior on sigma2.
#' @param b0 The scale parameter for the prior on sigma2.
#'
#' @return The current log-posterior.
NULL

#' Log-posterior for LDA model
#'
#' @param ll A double of the current log-likelihood.
#' @param theta A D x K matrix of the current estimates of the document topic proportions.
#' @param beta a K x V matrix of the current estimates of the word-topic probabilities.
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions.
#' @param V The number of words in the vocabulary.
#' @param docs_index A vector of length D containing elements 1, 2, ..., D.
#'
#' @return The current log-posterior.
NULL

#' Log-posterior for sLDA/sLDAX model
#'
#' @param ll A double of the current log-likelihood.
#' @param eta A q x 1 vector of regression coefficients.
#' @param sigma2 The current draw of the residual variance of y.
#' @param theta A D x K matrix of the current estimates of the document topic proportions.
#' @param beta a K x V matrix of the current estimates of the word-topic probabilities.
#' @param mu0 A q x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A q x q variance-covariance matrix for the prior on the
#'   regression coefficients.
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions.
#' @param a0 The shape parameter for the prior on sigma2.
#' @param b0 The scale parameter for the prior on sigma2.
#' @param V The number of words in the vocabulary.
#' @param docs_index A vector of length D containing elements 1, 2, ..., D.
#'
#' @return The current log-posterior.
NULL

#' Log-posterior for logistic sLDA/sLDAX model
#'
#' @param ll A double of the current log-likelihood.
#' @param eta A q x 1 vector of regression coefficients.
#' @param theta A D x K matrix of the current estimates of the document topic proportions.
#' @param beta a K x V matrix of the current estimates of the word-topic probabilities.
#' @param mu0 A q x 1 mean vector for the prior on the regression coefficients.
#' @param sigma0 A q x q variance-covariance matrix for the prior on the
#'   regression coefficients.
#' @param gamma_ The hyper-parameter for the prior on the topic-specific
#'   vocabulary probabilities.
#' @param alpha_ The hyper-parameter for the prior on the topic proportions.
#' @param V The number of words in the vocabulary.
#' @param docs_index A vector of length D containing elements 1, 2, ..., D.
#'
#' @return The current log-posterior.
NULL

#' Update number of times topic was drawn in document excluding current word
#'
#' @param topic The current topic index.
#' @param ndk A vector of the current number of draws of each topic in document d.
#'
#' @return A vector of the current number of draws of each topic in document d
#'   excluding word n.
NULL

#' Update number of times topic was drawn in corpus excluding current word
#'
#' @param topic The current topic index.
#' @param nk A vector of the current number of draws of each topic in the corpus.
#'
#' @return A vector of the current number of draws of each topic in the corpus
#'   excluding the current word.
NULL

#' Update number of times word and topic co-occur in corpus
#'
#' @param word The current word index.
#' @param topic The current topic index.
#' @param nkm A K x V matrix of the current number of co-occurences of each topic
#'   and vocabulary term in the corpus.
#'
#' @return A K x V matrix of the current number of co-occurences of each topic
#'   and vocabulary term in the corpus excluding the current word.
NULL

#' Update all topic and topic-word counts in document and corpus
#'
#' @param d The current document index.
#' @param word The current word index.
#' @param topic The current topic index.
#' @param ndk A vector of the current number of draws of each topic in document d.
#' @param nk A vector of the current number of draws of each topic in the corpus.
#' @param nkm A K x V matrix of the current number of co-occurences of each topic
#'   and vocabulary term in the corpus.
NULL

#' @export
.est_betak <- function(wz_co, gamma_) {
    .Call(`_psychtm_est_betak`, wz_co, gamma_)
}

#' @export
.est_thetad <- function(z_count, alpha_) {
    .Call(`_psychtm_est_thetad`, z_count, alpha_)
}

#' @export
.count_topic_word <- function(K, V, doc_topic, doc_word) {
    .Call(`_psychtm_count_topic_word`, K, V, doc_topic, doc_word)
}

#' Compute WAIC for all outcomes.
#'
#' @param iter The current iteration of the chain.
#' @param l_pred A m x D matrix of predictive likelihoods (NOT log-likelihoods).
#'
#' @return Vector of (1) WAIC for model, (2) standard error for WAIC, and (3)
#'   the effective number of parameters.
#' @export
waic_all <- function(iter, l_pred) {
    .Call(`_psychtm_waic_all`, iter, l_pred)
}

#' Compute difference (WAIC1 - WAIC2) in WAIC and its SE for two models.
#'
#' @param l_pred1 A m1 x D matrix of predictive likelihoods (NOT log-likelihoods) from model 1.
#' @param l_pred2 A m2 x D matrix of predictive likelihoods (NOT log-likelihoods) from model 2.
#'
#' @return A vector of (1) the difference in WAIC (on the deviance scale)
#'   between models and (2) the standard error of the difference in WAIC.
#' @export
waic_diff <- function(l_pred1, l_pred2) {
    .Call(`_psychtm_waic_diff`, l_pred1, l_pred2)
}

#' @export
.gibbs_mlr_cpp <- function(m, burn, thin, y, x, mu0, sigma0, eta_start, a0 = 0.001, b0 = 0.001, verbose = FALSE, display_progress = FALSE) {
    .Call(`_psychtm_gibbs_mlr_cpp`, m, burn, thin, y, x, mu0, sigma0, eta_start, a0, b0, verbose, display_progress)
}

#' @export
.gibbs_logistic_cpp <- function(m, burn, thin, y, x, mu0, sigma0, eta_start, proposal_sd, verbose = FALSE, display_progress = FALSE) {
    .Call(`_psychtm_gibbs_logistic_cpp`, m, burn, thin, y, x, mu0, sigma0, eta_start, proposal_sd, verbose, display_progress)
}

#' @export
.gibbs_sldax_cpp <- function(docs, V, m, burn, thin, K, model, y, x, mu0, sigma0, a0, b0, eta_start, proposal_sd, interaction_xcol = -1L, alpha_ = 0.1, gamma_ = 1.01, constrain_eta = TRUE, verbose = FALSE, display_progress = FALSE) {
    .Call(`_psychtm_gibbs_sldax_cpp`, docs, V, m, burn, thin, K, model, y, x, mu0, sigma0, a0, b0, eta_start, proposal_sd, interaction_xcol, alpha_, gamma_, constrain_eta, verbose, display_progress)
}

